Algoritmo "terreno"

Var

   largura, comprimento, metroquadrado, area, preco : real

Inicio

   escreva("Digite a largura do terreno: ")
   leia(largura)
   escreva("Digite o comprimento do terreno: ")
   leia(comprimento)
   escreva("Digite o valor do metro quadrado: ")
   leia(metroquadrado)
   
   area <- largura * comprimento
   preco <- area * metroquadrado

   escreval("Area do terreno = ", area:8:2)
   escreval("Preço do terreno = ", preco:8:2)

Fimalgoritmo